### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by spencerpogo** [dpren/react-pixel-grid#2]
The `import` statements inside this library aren't working for me.

**Comment by dpren** [comment]
Could you provide a little more detail? Which import statement are you using? Any error message?

Thanks

**Comment by spencerpogo** [comment]
Sorry for the lack of detail. Here is how to reproduce the issue:
```sh
npx create-next-app react-pixel-grid-bug
cd react-pixel-grid-bug
npm i react-pixel-grid
```
Then, put this into `pages/index.js`:
```jsx
import Grid from "react-pixel-grid";

export default function Index() {
  const r = "#f00";
  const g = "#0f0";
  const b = "#00f";
  const x = "#000";
   
  return <PixelGrid data={[
      x, r, x, g, x, b, 
      r, x, g, x, b, x, 
      x, r, x, g, x, b, 
      r, x, g, x, b, x, 
      x, r, x, g, x, b, 
      r, x, g, x, b, x,
  ]} />
}
```
Finally, start the server with `npm run dev` and open `http://localhost:3000`. An error pops up with the referenced syntax error and a traceback. 

![The error in browser](https://user-images.githubusercontent.com/34356756/119858215-1aaa3b80-bec9-11eb-8af6-008526a6cc7e.png)

The error in terminal:
```
/home/scoder12/code/react-pixel-grid/node_modules/react-pixel-grid/dist/PixelGrid.js:1
import _toConsumableArray from "@babel/runtime/helpers/esm/toConsumableArray";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.react-pixel-grid (/home/scoder12/code/react-pixel-grid/.next/server/pages/index.js:33:18)
    at __webpack_require__ (/home/scoder12/code/react-pixel-grid/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:7:74)
    at Object../pages/index.js (/home/scoder12/code/react-pixel-grid/.next/server/pages/index.js:22:1)
    at __webpack_require__ (/home/scoder12/code/react-pixel-grid/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/scoder12/code/react-pixel-grid/.next/server/pages/index.js:54:52)
    at /home/scoder12/code/react-pixel-grid/.next/server/pages/index.js:55:28
    at Object.<anonymous> (/home/scoder12/code/react-pixel-grid/.next/server/pages/index.js:58:3)
```

**Comment by dpren** [comment]
Next.js is using a newer version of webpack (v5), that has some broken backwards compatibility. That sucks. I'll look into it deeper if I have time... Otherwise you might have luck googling around for the `_toConsumableArray` error. Or use an older version of Next that uses webpack 4.

Unrelated, you'll want to import `PixelGrid` not `Grid` :)  And probably `npm i` with the `-S` save flag.

**Comment by spencerpogo** [comment]
Thanks for the clarification.
